import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import type { BriefOutput } from '@/types';

// ─── Props ───────────────────────────────────────────────────────────────────

export interface PdfDocumentProps {
  brief: BriefOutput;
  keyword: string;
  intent: string;
  targetCountry: string | null;
  websiteName: string | null;
  websiteDomain: string | null;
  websiteLogoUrl: string | null;
  isAgency: boolean;
}

// ─── Styles ──────────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Helvetica',
    backgroundColor: '#ffffff',
  },
  coverPage: {
    padding: 40,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#080b14',
  },
  coverTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#ffffff',
    marginTop: 40,
    textAlign: 'center',
  },
  coverSubtitle: {
    fontSize: 14,
    color: '#a78bfa',
    marginTop: 12,
    textAlign: 'center',
  },
  coverMeta: {
    fontSize: 11,
    color: '#94a3b8',
    marginTop: 8,
    textAlign: 'center',
  },
  coverDate: {
    fontSize: 10,
    color: '#64748b',
    marginTop: 40,
    textAlign: 'center',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#7c3aed',
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
    paddingBottom: 8,
  },
  label: {
    fontSize: 10,
    color: '#64748b',
    marginBottom: 4,
    fontWeight: 'bold',
  },
  value: {
    fontSize: 11,
    color: '#1e293b',
    marginBottom: 12,
    lineHeight: 1.5,
  },
  fieldGroup: {
    marginBottom: 12,
  },
  row: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 8,
  },
  col: {
    flex: 1,
  },
  outlineItem: {
    marginBottom: 10,
  },
  outlineH2: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#7c3aed',
    marginBottom: 4,
  },
  outlineH3: {
    fontSize: 11,
    color: '#334155',
    marginLeft: 12,
    marginBottom: 2,
  },
  outlineNote: {
    fontSize: 10,
    color: '#64748b',
    marginLeft: 12,
    marginBottom: 6,
    fontStyle: 'italic',
  },
  statItem: {
    marginBottom: 8,
    paddingLeft: 8,
    borderLeftWidth: 2,
    borderLeftColor: '#7c3aed',
  },
  statClaim: {
    fontSize: 11,
    color: '#1e293b',
    marginBottom: 2,
  },
  statSource: {
    fontSize: 9,
    color: '#64748b',
  },
  quoteItem: {
    marginBottom: 10,
    paddingLeft: 8,
    borderLeftWidth: 2,
    borderLeftColor: '#10b981',
  },
  quoteText: {
    fontSize: 10,
    color: '#334155',
    fontStyle: 'italic',
    marginBottom: 2,
  },
  quoteSource: {
    fontSize: 9,
    color: '#64748b',
  },
  faqItem: {
    marginBottom: 10,
  },
  faqQuestion: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#1e293b',
    marginBottom: 2,
  },
  faqAnswer: {
    fontSize: 10,
    color: '#475569',
    lineHeight: 1.4,
  },
  schemaBlock: {
    backgroundColor: '#f8fafc',
    padding: 12,
    borderRadius: 4,
    fontFamily: 'Courier',
    fontSize: 8,
    color: '#1e293b',
    lineHeight: 1.3,
  },
  footer: {
    position: 'absolute',
    bottom: 20,
    left: 40,
    right: 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
    fontSize: 8,
    color: '#94a3b8',
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    paddingTop: 8,
  },
  table: {
    marginBottom: 12,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#f1f5f9',
    padding: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  tableHeaderCell: {
    fontSize: 9,
    fontWeight: 'bold',
    color: '#475569',
    flex: 1,
  },
  tableRow: {
    flexDirection: 'row',
    padding: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  tableCell: {
    fontSize: 9,
    color: '#334155',
    flex: 1,
  },
  comparisonVerdict: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#7c3aed',
    marginTop: 8,
  },
});

// ─── Footer Component ────────────────────────────────────────────────────────

interface PdfFooterProps {
  today: string;
}

function PdfFooter({ today }: PdfFooterProps): React.ReactElement {
  return (
    <Text style={styles.footer} fixed>
      <Text>{`Generated by WasafSEO — ${today}`}</Text>
      <Text
        style={{ fontSize: 8, color: '#94a3b8' }}
        render={({ pageNumber, totalPages }: { pageNumber: number; totalPages: number }): string =>
          `${pageNumber} / ${totalPages}`
        }
      />
    </Text>
  );
}

// ─── PDF Document ────────────────────────────────────────────────────────────

export function WasafPdfDocument({
  brief,
  keyword,
  intent,
  targetCountry,
  websiteName,
  websiteDomain,
  isAgency,
}: PdfDocumentProps): React.ReactElement {
  const { fundamentals, content } = brief;
  const today = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const schemaString = JSON.stringify(brief, null, 2);

  return (
    <Document>
      {/* ── Cover Page ───────────────────────────────────────────────────── */}
      <Page size="A4" style={styles.coverPage}>
        <Text style={{ fontSize: 40, fontWeight: 'bold', color: '#7c3aed' }}>
          {isAgency && websiteName ? websiteName : 'WasafSEO'}
        </Text>
        <Text style={styles.coverTitle}>{fundamentals.pageTitle || keyword}</Text>
        <Text style={styles.coverSubtitle}>Arabic SEO Content Brief</Text>
        {websiteName && (
          <Text style={styles.coverMeta}>
            {websiteName}{websiteDomain ? ` — ${websiteDomain}` : ''}
          </Text>
        )}
        <Text style={styles.coverDate}>Generated on {today}</Text>
      </Page>

      {/* ── Page 1: Fundamentals ─────────────────────────────────────────── */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionTitle}>Fundamentals</Text>

        <View style={styles.fieldGroup}>
          <Text style={styles.label}>Page Title</Text>
          <Text style={styles.value}>{fundamentals.pageTitle}</Text>
        </View>

        <View style={styles.fieldGroup}>
          <Text style={styles.label}>Meta Description</Text>
          <Text style={styles.value}>{fundamentals.metaDescription}</Text>
        </View>

        <View style={styles.row}>
          <View style={styles.col}>
            <Text style={styles.label}>Slug</Text>
            <Text style={styles.value}>{fundamentals.slug}</Text>
          </View>
          <View style={styles.col}>
            <Text style={styles.label}>Estimated Word Count</Text>
            <Text style={styles.value}>{fundamentals.estimatedWordCount}</Text>
          </View>
        </View>

        <View style={styles.row}>
          <View style={styles.col}>
            <Text style={styles.label}>Search Intent</Text>
            <Text style={styles.value}>{fundamentals.searchIntent}</Text>
          </View>
          <View style={styles.col}>
            <Text style={styles.label}>Target Location</Text>
            <Text style={styles.value}>{fundamentals.targetLocation}</Text>
          </View>
        </View>

        <View style={styles.fieldGroup}>
          <Text style={styles.label}>Primary Keyword</Text>
          <Text style={styles.value}>{fundamentals.primaryKeyword}</Text>
        </View>

        <Text style={[styles.sectionTitle, { marginTop: 24 }]}>Keyword & Context</Text>

        <View style={styles.row}>
          <View style={styles.col}>
            <Text style={styles.label}>Keyword</Text>
            <Text style={styles.value}>{keyword}</Text>
          </View>
          <View style={styles.col}>
            <Text style={styles.label}>Intent</Text>
            <Text style={styles.value}>{intent}</Text>
          </View>
        </View>

        {targetCountry && (
          <View style={styles.fieldGroup}>
            <Text style={styles.label}>Target Country</Text>
            <Text style={styles.value}>{targetCountry}</Text>
          </View>
        )}

        <Text style={styles.sectionTitle}>Direct Answer</Text>
        <Text style={styles.value}>{content.directAnswer?.text}</Text>

        <Text style={styles.sectionTitle}>TL;DR</Text>
        <Text style={styles.value}>{content.tldr?.heading}</Text>
        {content.tldr?.points?.map((point: string, i: number) => (
          <Text key={i} style={[styles.value, { marginLeft: 12 }]}>
            • {point}
          </Text>
        ))}

        <PdfFooter today={today} />
      </Page>

      {/* ── Page 2: Content Outline ──────────────────────────────────────── */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionTitle}>Content Structure</Text>

        <Text style={styles.label}>H1 Heading</Text>
        <Text style={styles.value}>{content.h1}</Text>

        <Text style={[styles.sectionTitle, { marginTop: 16 }]}>Outline</Text>

        {content.outline?.map((section, idx: number) => (
          <View key={idx} style={styles.outlineItem}>
            <Text style={styles.outlineH2}>
              H2: {section.h2}
            </Text>
            {section.h3s?.map((h3, h3Idx: number) => (
              <View key={h3Idx}>
                <Text style={styles.outlineH3}>
                  H3: {h3.heading}
                </Text>
                {h3.notes && (
                  <Text style={styles.outlineNote}>{h3.notes}</Text>
                )}
              </View>
            ))}
            {section.contentNotes && (
              <Text style={styles.outlineNote}>
                Note: {section.contentNotes}
              </Text>
            )}
          </View>
        ))}

        <PdfFooter today={today} />
      </Page>

      {/* ── Page 3: GEO Elements ─────────────────────────────────────────── */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionTitle}>GEO / AIO Elements</Text>

        {/* Stats */}
        {content.stats && content.stats.length > 0 && (
          <>
            <Text style={[styles.sectionTitle, { fontSize: 14 }]}>Statistics</Text>
            {content.stats.map((stat, i: number) => (
              <View key={i} style={styles.statItem}>
                <Text style={styles.statClaim}>{stat.claim}</Text>
                <Text style={styles.statSource}>
                  Source: {stat.sourceOrg} ({stat.sourceType}, {stat.year})
                </Text>
              </View>
            ))}
          </>
        )}

        {/* Expert Quotes */}
        {content.expertQuotes && content.expertQuotes.length > 0 && (
          <>
            <Text style={[styles.sectionTitle, { fontSize: 14, marginTop: 16 }]}>Expert Quotes</Text>
            {content.expertQuotes.map((quote, i: number) => (
              <View key={i} style={styles.quoteItem}>
                <Text style={styles.quoteText}>"{quote.quoteText}"</Text>
                <Text style={styles.quoteSource}>
                  — {quote.suggestedName}, {quote.suggestedTitle} at {quote.suggestedOrg}
                </Text>
              </View>
            ))}
          </>
        )}

        {/* Comparison Table */}
        {content.comparisonTable && (
          <>
            <Text style={[styles.sectionTitle, { fontSize: 14, marginTop: 16 }]}>
              Comparison Table
            </Text>
            <Text style={[styles.value, { fontStyle: 'italic' }]}>
              {content.comparisonTable.caption}
            </Text>
            <View style={styles.table}>
              <View style={styles.tableHeader}>
                {content.comparisonTable.headers.map((header: string, i: number) => (
                  <Text key={i} style={styles.tableHeaderCell}>{header}</Text>
                ))}
              </View>
              {content.comparisonTable.rows.map((row: string[], i: number) => (
                <View key={i} style={styles.tableRow}>
                  {row.map((cell: string, j: number) => (
                    <Text key={j} style={styles.tableCell}>{cell}</Text>
                  ))}
                </View>
              ))}
            </View>
            <Text style={styles.comparisonVerdict}>
              Verdict: {content.comparisonTable.verdict}
            </Text>
          </>
        )}

        {/* FAQ */}
        {content.faq && content.faq.length > 0 && (
          <>
            <Text style={[styles.sectionTitle, { fontSize: 14, marginTop: 16 }]}>FAQ</Text>
            {content.faq.map((item, i: number) => (
              <View key={i} style={styles.faqItem}>
                <Text style={styles.faqQuestion}>Q: {item.question}</Text>
                <Text style={styles.faqAnswer}>A: {item.answer}</Text>
              </View>
            ))}
          </>
        )}

        <PdfFooter today={today} />
      </Page>

      {/* ── Page 4+: JSON-LD Schema ──────────────────────────────────────── */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionTitle}>JSON-LD Schema</Text>

        <Text style={styles.value}>
          The following structured data schema should be added to the page in a
          {' '}
          {'<script type="application/ld+json">'}
          {' '}tag within the {' '}
          {'<head>'}
          {' '}section.
        </Text>

        <View style={styles.schemaBlock}>
          <Text>{schemaString}</Text>
        </View>

        <PdfFooter today={today} />
      </Page>
    </Document>
  );
}
