import { createAdminClient } from '@/lib/supabase/admin';
import { getCurrentMonth, getPlanLimit, isTrialActive } from '@/lib/utils';
import type { PlanType } from '@/types';

/**
 * Retrieves the number of briefs generated by a user in the current month.
 * @param userId - The user's UUID
 * @returns The number of briefs generated this month (0 if no record exists)
 */
export async function getMonthlyUsage(userId: string): Promise<number> {
  const supabase = createAdminClient();
  const month = getCurrentMonth();

  const { data, error } = await supabase
    .from('usage')
    .select('briefs_generated')
    .eq('user_id', userId)
    .eq('month', month)
    .single();

  if (error) {
    // PGRST116 = no rows found, user has no usage record yet
    if (error.code === 'PGRST116') return 0;
    throw new Error(`Failed to fetch monthly usage: ${error.message}`);
  }

  return data?.briefs_generated ?? 0;
}

/**
 * Checks if a user has reached their monthly brief generation limit.
 * Returns detailed result including current count, limit, and Arabic error message.
 */
export async function checkUsageLimit(
  userId: string,
  plan: PlanType,
  trialEndsAt: string | null
): Promise<{
  allowed: boolean;
  current: number;
  limit: number;
  message: string;
}> {
  const isInTrial = plan === 'starter' && isTrialActive(trialEndsAt);
  const limit = getPlanLimit(plan, isInTrial);

  // No plan — block with subscription message
  if (plan === 'none') {
    return {
      allowed: false,
      current: 0,
      limit: 0,
      message: 'No active subscription. Please subscribe to continue.',
    };
  }

  // Agency/unlimited — always allowed
  if (limit === Infinity) {
    return {
      allowed: true,
      current: 0,
      limit: Infinity,
      message: '',
    };
  }

  const current = await getMonthlyUsage(userId);

  if (current >= limit) {
    return {
      allowed: false,
      current,
      limit,
      message: 'You have reached your monthly brief limit. Please upgrade your plan to continue.',
    };
  }

  return {
    allowed: true,
    current,
    limit,
    message: '',
  };
}

/**
 * Increments the user's brief generation count for the current month.
 * Uses upsert to handle first-time usage and concurrent requests.
 * @param userId - The user's UUID
 */
export async function incrementUsage(userId: string): Promise<void> {
  const supabase = createAdminClient();
  const month = getCurrentMonth();

  const { error } = await supabase
    .from('usage')
    .upsert(
      {
        user_id: userId,
        month,
        briefs_generated: 1,
      },
      {
        onConflict: 'user_id,month',
        ignoreDuplicates: false,
      }
    );

  if (error) {
    throw new Error(`Failed to increment usage: ${error.message}`);
  }
}
