import Link from 'next/link';
import {
  Sparkles,
  FileText,
  Code,
  Globe,
  ShieldCheck,
  MapPin,
  X,
  Check,
  ArrowLeft,
  Star,
  ChevronRight,
} from 'lucide-react';

// ─── Constants ────────────────────────────────────────────────────────────────

interface Testimonial {
  name: string;
  role: string;
  company: string;
  quote: string;
}

const TESTIMONIALS: Testimonial[] = [
  {
    name: 'Ahmed Al-Mansouri',
    role: 'SEO Manager',
    company: 'TechHub Arabia',
    quote:
      'WasafSEO cut our Arabic content briefing time by 80%. The JSON-LD schema generation alone saves us hours of manual work.',
  },
  {
    name: 'Layla Bint Hassan',
    role: 'Content Director',
    company: 'Sahara Digital',
    quote:
      'The GEO optimization features are exactly what we needed. Our Arabic content is now appearing in AI answer engines consistently.',
  },
  {
    name: 'Omar Al-Rashid',
    role: 'Founder',
    company: 'Qibla Marketing',
    quote:
      'Finally, a tool that understands Arabic SEO deeply. The E-E-A-T signals and structured data are production-ready.',
  },
];

// ─── Section: Hero ────────────────────────────────────────────────────────────

function HeroSection(): React.ReactElement {
  return (
    <section className="relative overflow-hidden px-4 pb-20 pt-12 lg:pb-32 lg:pt-20">
      {/* Violet glow behind headline */}
      <div className="pointer-events-none absolute inset-0 flex items-start justify-center">
        <div className="h-[500px] w-[500px] translate-y-[-10%] rounded-full bg-primary/20 blur-[120px] lg:h-[700px] lg:w-[700px]" />
      </div>

      <div className="relative mx-auto max-w-5xl text-center">
        {/* Badge */}
        <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/10 px-4 py-1.5">
          <Sparkles size={14} className="text-primary-light" />
          <span className="text-xs font-medium text-primary-light">
            AI-Powered Arabic SEO Platform
          </span>
        </div>

        {/* Headline */}
        <h1 className="font-display text-4xl font-extrabold leading-tight text-text-primary sm:text-5xl lg:text-6xl">
          Arabic Content{' '}
          <span className="bg-gradient-to-r from-primary-light to-primary bg-clip-text text-transparent">
            That Ranks
          </span>
        </h1>

        {/* Subtitle */}
        <p className="mx-auto mt-6 max-w-2xl text-base leading-relaxed text-text-muted lg:text-lg">
          Generate complete Arabic SEO briefs with JSON-LD schema, GEO optimization,
          and E-E-A-T signals — in seconds. Built for the Arab web.
        </p>

        {/* CTA Buttons */}
        <div className="mt-8 flex flex-col items-center justify-center gap-4 sm:flex-row">
          <Link
            href="/login"
            className="flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-primary px-8 text-sm font-semibold text-white shadow-lg shadow-primary/25 transition-all hover:bg-primary-dark focus:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-surface active:scale-95 sm:w-auto"
          >
            Start Free Trial
            <ChevronRight size={16} />
          </Link>
          <Link
            href="#how-it-works"
            className="flex h-12 w-full items-center justify-center gap-2 rounded-xl border border-surface-border px-8 text-sm font-medium text-text-muted transition-all hover:bg-surface-card hover:text-text-primary focus:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-surface active:scale-95 sm:w-auto"
          >
            See How It Works
          </Link>
        </div>

        {/* Trust badges */}
        <div className="mt-6 flex flex-wrap items-center justify-center gap-x-6 gap-y-2">
          {['3-day free trial', 'No credit card', 'Cancel anytime'].map((text) => (
            <span
              key={text}
              className="flex items-center gap-1.5 text-xs text-text-muted"
            >
              <Check size={14} className="text-success" />
              {text}
            </span>
          ))}
        </div>

        {/* Preview Card */}
        <div className="mx-auto mt-12 max-w-3xl rounded-2xl border border-surface-border bg-surface-card/80 p-6 backdrop-blur-sm lg:p-8">
          <div className="flex items-center gap-3 border-b border-surface-border pb-4">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary/20">
              <FileText size={16} className="text-primary-light" />
            </div>
            <div className="text-left">
              <p className="text-sm font-medium text-text-primary">
                SEO Content Brief
              </p>
              <p className="text-xs text-text-muted">
                Generated by WasafSEO AI
              </p>
            </div>
          </div>
          <div className="mt-4 space-y-3 text-left">
            <div>
              <span className="text-xs font-medium text-text-muted">
                TITLE
              </span>
              <p className="text-sm font-medium text-text-primary">
                أفضل 10 استراتيجيات تحسين محركات البحث في السعودية 2026
              </p>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <span className="text-xs font-medium text-text-muted">
                  WORD COUNT
                </span>
                <p className="text-sm text-text-primary">2,500–3,000</p>
              </div>
              <div>
                <span className="text-xs font-medium text-text-muted">
                  INTENT
                </span>
                <p className="text-sm text-text-primary">Informational</p>
              </div>
            </div>
            <div className="flex flex-wrap gap-2">
              {[
                'JSON-LD ✓',
                'FAQ ✓',
                'Statistics ✓',
                'E-E-A-T ✓',
              ].map((tag) => (
                <span
                  key={tag}
                  className="rounded-full bg-primary/10 px-2.5 py-0.5 text-[11px] font-medium text-primary-light"
                >
                  {tag}
                </span>
              ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

// ─── Section: Problem ─────────────────────────────────────────────────────────

function ProblemSection(): React.ReactElement {
  const problems = [
    {
      title: 'Unstructured Arabic Content',
      description:
        'No SEO strategy leads to poor rankings. Arabic content needs specialized optimization that generic tools cannot provide.',
    },
    {
      title: 'Missing Structured Data',
      description:
        'Without JSON-LD schema, your content is invisible to AI answer engines, rich snippets, and voice search results.',
    },
    {
      title: 'Ignored by AI Engines',
      description:
        'Traditional SEO alone is not enough. Google SGE, ChatGPT, and Perplexity need GEO-optimized content to cite your pages.',
    },
  ];

  return (
    <section
      id="problem"
      className="border-t border-surface-border px-4 py-16 lg:py-24"
    >
      <div className="mx-auto max-w-5xl">
        <h2 className="text-center font-display text-2xl font-bold text-text-primary lg:text-3xl">
          Why Arabic Content Fails to Rank
        </h2>
        <p className="mx-auto mt-3 max-w-xl text-center text-sm text-text-muted lg:text-base">
          Generic SEO tools do not understand Arabic content structure, cultural
          context, or regional search intent.
        </p>

        <div className="mt-10 grid gap-6 md:grid-cols-3">
          {problems.map(({ title, description }) => (
            <div
              key={title}
              className="rounded-2xl border border-surface-border bg-surface-card p-6"
            >
              <div className="mb-4 flex h-10 w-10 items-center justify-center rounded-lg bg-error/10">
                <X size={20} className="text-error" />
              </div>
              <h3 className="text-base font-semibold text-text-primary lg:text-lg">
                {title}
              </h3>
              <p className="mt-2 text-sm leading-relaxed text-text-muted">
                {description}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

// ─── Section: Solution (Features) ─────────────────────────────────────────────

interface Feature {
  icon: React.ReactNode;
  title: string;
  description: string;
}

function SolutionSection(): React.ReactElement {
  const features: Feature[] = [
    {
      icon: <Sparkles size={22} className="text-primary-light" />,
      title: 'AI-Powered Arabic Briefs',
      description:
        'Deepseek-powered AI generates complete Arabic SEO briefs with perfect grammar, cultural relevance, and keyword optimization.',
    },
    {
      icon: <FileText size={22} className="text-primary-light" />,
      title: 'Complete Content Structure',
      description:
        'Every brief includes meta tags, H1-H3 outlines, direct answers, TL;DR, stats, expert quotes, FAQs, and more.',
    },
    {
      icon: <Code size={22} className="text-primary-light" />,
      title: 'Automatic JSON-LD Schema',
      description:
        'Generate Article, FAQPage, HowTo, and Product schema automatically — fully populated, no placeholders.',
    },
    {
      icon: <Globe size={22} className="text-primary-light" />,
      title: 'GEO / AIO Optimization',
      description:
        'Optimized for Google SGE, ChatGPT, Perplexity, and other AI answer engines. Get cited, not ignored.',
    },
    {
      icon: <ShieldCheck size={22} className="text-primary-light" />,
      title: 'E-E-A-T Signals Built-in',
      description:
        'Author bios, expert quotes, statistics with sources, and experience-based content that Google trusts.',
    },
    {
      icon: <MapPin size={22} className="text-primary-light" />,
      title: 'All GCC Countries Supported',
      description:
        'Target Saudi Arabia, UAE, Qatar, Kuwait, Bahrain, Oman, and more with country-specific optimization.',
    },
  ];

  return (
    <section
      id="features"
      className="border-t border-surface-border px-4 py-16 lg:py-24"
    >
      <div className="mx-auto max-w-5xl">
        <h2 className="text-center font-display text-2xl font-bold text-text-primary lg:text-3xl">
          Everything You Need for{' '}
          <span className="text-primary-light">Arabic SEO</span>
        </h2>
        <p className="mx-auto mt-3 max-w-xl text-center text-sm text-text-muted lg:text-base">
          One platform. Complete Arabic SEO content briefs. No generic templates.
        </p>

        <div className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {features.map(({ icon, title, description }) => (
            <div
              key={title}
              className="group rounded-2xl border border-surface-border bg-surface-card p-6 transition-all hover:border-primary/30 hover:shadow-lg hover:shadow-primary/5"
            >
              <div className="mb-4 flex h-11 w-11 items-center justify-center rounded-lg bg-primary/10 transition-colors group-hover:bg-primary/20 lg:h-12 lg:w-12">
                {icon}
              </div>
              <h3 className="text-base font-semibold text-text-primary lg:text-lg">
                {title}
              </h3>
              <p className="mt-2 text-sm leading-relaxed text-text-muted">
                {description}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

// ─── Section: How It Works ────────────────────────────────────────────────────

function HowItWorksSection(): React.ReactElement {
  const steps = [
    {
      number: '01',
      title: 'Enter Your Keyword',
      description:
        'Type any keyword in any language — Arabic, English, or mixed. WasafSEO handles it all.',
    },
    {
      number: '02',
      title: 'Set Intent & Target',
      description:
        'Choose search intent (informational, commercial, how-to, comparison) and target GCC country.',
    },
    {
      number: '03',
      title: 'Get Your Brief',
      description:
        'Receive a complete Arabic SEO brief with JSON-LD schema, GEO optimization, and E-E-A-T signals.',
    },
  ];

  return (
    <section
      id="how-it-works"
      className="border-t border-surface-border px-4 py-16 lg:py-24"
    >
      <div className="mx-auto max-w-5xl">
        <h2 className="text-center font-display text-2xl font-bold text-text-primary lg:text-3xl">
          How It Works
        </h2>
        <p className="mx-auto mt-3 max-w-xl text-center text-sm text-text-muted lg:text-base">
          Three simple steps to a production-ready Arabic content brief.
        </p>

        <div className="mt-12 grid gap-8 md:grid-cols-3">
          {steps.map(({ number, title, description }, index) => (
            <div key={number} className="relative text-center">
              {/* Connector line */}
              {index < steps.length - 1 && (
                <div className="absolute left-[60%] top-8 hidden h-px w-[80%] border-t border-dashed border-primary/20 md:block" />
              )}

              <div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-primary/10 text-xl font-bold text-primary-light">
                {number}
              </div>
              <h3 className="mt-5 text-base font-semibold text-text-primary lg:text-lg">
                {title}
              </h3>
              <p className="mt-2 text-sm leading-relaxed text-text-muted">
                {description}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

// ─── Section: Social Proof ────────────────────────────────────────────────────

function SocialProofSection(): React.ReactElement {
  const stats = [
    { value: '500+', label: 'Briefs Generated' },
    { value: '10', label: 'Countries' },
    { value: '95%', label: 'Satisfaction' },
  ];

  return (
    <section className="border-t border-surface-border px-4 py-16 lg:py-24">
      <div className="mx-auto max-w-5xl">
        {/* Stats */}
        <div className="mb-12 grid grid-cols-3 gap-6 text-center">
          {stats.map(({ value, label }) => (
            <div key={label}>
              <p className="font-display text-3xl font-bold text-primary-light lg:text-4xl">
                {value}
              </p>
              <p className="mt-1 text-xs text-text-muted lg:text-sm">{label}</p>
            </div>
          ))}
        </div>

        {/* Testimonials */}
        <div className="grid gap-6 md:grid-cols-3">
          {TESTIMONIALS.map(({ name, role, company, quote }) => (
            <div
              key={name}
              className="rounded-2xl border border-surface-border bg-surface-card p-6"
            >
              {/* Stars */}
              <div className="mb-4 flex gap-1">
                {Array.from({ length: 5 }).map((_, i) => (
                  <Star
                    key={i}
                    size={14}
                    className="fill-amber-400 text-amber-400"
                  />
                ))}
              </div>

              <p className="text-sm leading-relaxed text-text-muted">
                &ldquo;{quote}&rdquo;
              </p>

              <div className="mt-4 border-t border-surface-border pt-4">
                <p className="text-sm font-medium text-text-primary">{name}</p>
                <p className="text-xs text-text-muted">
                  {role}, {company}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

// ─── Section: CTA ─────────────────────────────────────────────────────────────

function CTASection(): React.ReactElement {
  return (
    <section className="px-4 py-16 lg:py-24">
      <div className="mx-auto max-w-3xl">
        <div className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-primary to-primary-dark px-6 py-12 text-center shadow-2xl shadow-primary/25 lg:px-12 lg:py-16">
          {/* Background pattern */}
          <div className="pointer-events-none absolute inset-0 opacity-10">
            <div className="absolute -left-10 -top-10 h-40 w-40 rounded-full bg-white blur-3xl" />
            <div className="absolute -bottom-10 -right-10 h-60 w-60 rounded-full bg-white blur-3xl" />
          </div>

          <h2 className="relative font-display text-2xl font-bold text-white lg:text-4xl">
            Start Ranking Arabic Content Today
          </h2>
          <p className="relative mx-auto mt-4 max-w-md text-sm text-white/80 lg:text-base">
            Join 500+ content creators who trust WasafSEO for their Arabic SEO
            content strategy.
          </p>

          <div className="relative mt-8 flex flex-col items-center justify-center gap-4 sm:flex-row">
            <Link
              href="/login"
              className="flex h-12 items-center justify-center rounded-xl bg-white px-8 text-sm font-semibold text-primary shadow-lg transition-all hover:bg-white/90 focus:outline-none focus-visible:ring-2 focus-visible:ring-white focus-visible:ring-offset-2 focus-visible:ring-offset-primary active:scale-95"
            >
              Start Your Free Trial &mdash; 3 Days Free
            </Link>
          </div>

          <p className="relative mt-4 text-xs text-white/60">
            No credit card required. Cancel anytime.
          </p>
        </div>
      </div>
    </section>
  );
}

// ─── Home Page ─────────────────────────────────────────────────────────────────

export default function HomePage(): React.ReactElement {
  return (
    <>
      <HeroSection />
      <ProblemSection />
      <SolutionSection />
      <HowItWorksSection />
      <SocialProofSection />
      <CTASection />
    </>
  );
}
